Sodam/Sodam/Delegate/SceneDelegate.swift, Sodam/Sodam/Extension/+UIColor.swift, Sodam/Sodam/Main/CustomTabBar.swift, Sodam/Sodam/Main/CustomTabBarController.swift, Sodam/Sodam/Main/MainViewController.swift, Sodam/Sodam/MemoryViewController.swift, Sodam/Sodam/SettingsViewController.swift
탭바 UI 구현 및 컬러 추가 
컬러 두개 추가한거는 피그마에 있던 그 저희가 쓰는 화이트랑 행복 작성하기 버튼 컬러 추가했습니다
=> [Feat] 탭바 UI 구현 및 컬러 2개 추가

Sodam/Sodam/Extension/+Array.swift, Sodam/Sodam/Extension/+UIStackView.swift, Sodam/Sodam/Extension/+UIView.swift, Sodam/Sodam/Setting/ReuseIdentifying.swift, Sodam/Sodam/Setting/Setting.swift, Sodam/Sodam/Setting/View/SettingTableViewCell.swift, Sodam/Sodam/Setting/View/SettingView.swift, Sodam/Sodam/UserDefaultsManager.swift
- notificationTime. isToggleNotification, content UserDefaultsManager에 작성
- 피그잼에 있는 id, imagePath는 어떻게 연결시켜야할지 감이 잘안와서 일단 미작성상태입니다.
예를들어 id 는 CoreData, imagePath는 FileManager의 데이터랑 UserDefault랑 각각 저장되는건지..?
- 파일도 폴더를 생성하려고했는데 CoreData,FileManager 와 함께 있으면 될것같아서 해당 파일 작업 후에 폴더 이동 시키겠습니다.
=> [Feat] UserDefaultsManager구현

Sodam/Sodam/Delegate/AppDelegate.swift, Sodam/Sodam/Delegate/SceneDelegate.swift, Sodam/Sodam/LocalNotificationManager.swift, Sodam/Sodam/Setting/SettingsViewController.swift, Sodam/Sodam/Setting/View/SettingTableViewCell.swift
- LocalNotification 기능 구현하여 사용자가 설정한 시간에 Notification 알림 적용
- 백그라운드, 포그라운드, switchOff 일때 확인완료
포그라운드
https://github.com/user-attachments/assets/3b494d6d-c400-4acc-90bf-9bbc4721cd20
백그라운드
- 알림 메시지 추천받습니당
- 앱아이콘 적용시 알림에 적용됩니다.
- pull 받은 후 테스트해보실때   SettingTableViewCell파일에서 timePicker.minuteInterval = 1 로 하고 1분단위로 바꿔서 테스트 해보심 됩니다! 혹시 다른 빠른 방법 아시는 분계시면 알려주세용!
=> [Feat] LocalNotifiacation 기능 구현

Sodam/Sodam.xcodeproj/project.pbxproj, Sodam/Sodam/Configuration/Info.plist, Sodam/Sodam/Main/View/CustomTabBarController.swift, Sodam/Sodam/Setting/SettingViewModel/SettingViewModel.swift, Sodam/Sodam/Setting/SettingsViewController.swift, Sodam/Sodam/Setting/View/SettingTableViewCell.swift
- SettingViewModel 추가하였습니다.
- SettingViewModel추가후 빌드 이상없는것으로 체크하였습니당!
=> [Feat] SettingView Refactor

Sodam/Sodam/HangdamStorage/HangdamStorageView.swift, Sodam/Sodam/HappinessList/HappinessListView.swift
탭바 사라지게 했습니다.
https://github.com/user-attachments/assets/0c35b639-4af0-4999-bbb2-bc60345d025b
사라지게 하는 메서드가 중복되는데 많진 않아서 그냥 각 뷰에 넣었습니다
=> [Fix] 탭바 사라지기 수정

Sodam/Sodam/CoreData/CoreDataManager.swift, Sodam/Sodam/CoreData/DTO/HappinessDTO.swift, Sodam/Sodam/CoreData/SodamContainer.xcdatamodeld/SodamContainer.xcdatamodel/contents, Sodam/Sodam/HangdamStatusView.swift, Sodam/Sodam/HangdamStorage/HangdamGridView.swift, Sodam/Sodam/HangdamStorage/HangdamStorageView.swift, Sodam/Sodam/HangdamStorage/HangdamStorageViewModel.swift, Sodam/Sodam/HappinessDetail/HappinessDetailView.swift, Sodam/Sodam/HappinessDetail/HappinessDetailViewModel.swift, Sodam/Sodam/HappinessList/HappinessListView.swift, Sodam/Sodam/HappinessList/HappinessListViewModel.swift, Sodam/Sodam/Helper/CustomAlert/CustomAlertBuilder.swift, Sodam/Sodam/Helper/CustomAlert/CustomAlertConfiguration.swift, Sodam/Sodam/Helper/CustomAlert/CustomAlertViewController.swift, Sodam/Sodam/Main/View/MainView.swift, Sodam/Sodam/Main/View/MainViewController.swift, Sodam/Sodam/Main/View/MainViewModel.swift, Sodam/Sodam/Repository/HangdamRepository.swift, Sodam/Sodam/Repository/HappinessRepository.swift, Sodam/Sodam/WriteView/WriteViewController.swift, Sodam/Sodam/WriteView/WriteViewModel.swift
코어데이터 연결 작업
MVVM으로 리팩터링 진행 중
https://github.com/user-attachments/assets/46bc7773-fd14-49de-afd0-bed05991b4d6
아직 메인 뷰에서 코어데이터에 데이터를 저장하는 부분을 구현하지 않아서 동작 확인을 전부 다 해보진 못했습니다.
코드만 보면서 짠 거라 한 번 이상한 부분 없는지 살펴봐주시면 감사하겠습니다. - 01.26 
메인뷰모델 구현 및 유저디폴츠를 코어데이터로 교체 완료
바보라는 이름으로 테스트했습니다. - 01.26
=> [Feat] 행담이 보관함 코어 데이터 연결 완료

Sodam/Sodam/Main/View/MainViewController.swift, Sodam/Sodam/Main/View/MainViewModel.swift
- 초기화 시점에 메세지 업데이트 추가
- WriteViewController에서 작성이 완료된 후에도 MainViewController로 돌아올 때 updateMessage()를 호출하도록 해서 랜덤메세지 보여주도록 했습니다 
알에서 깨어나는 시점은 어떻게 테스트 해볼 수 있을까요... gif 업데이트 되는지 궁금한데 어떤식으로 테스트 해야하는지 잘 모르겠습니다 ㅠ
=> [Fix] 메세지 잘 안나왔던 부분 수정

Sodam/Sodam/Setting/SettingViewModel/SettingViewModel.swift, Sodam/Sodam/Setting/SettingsViewController.swift
리뷰남기기 셀 탭시 애플스토어 리뷰 남기기로 이동 구현 추가
앱스토어 링크생성 후 교체 필요!
=> [Feat] 리뷰 남기기 링크 이동 추가

Sodam/Sodam/Setting/SettingViewModel/SettingViewModel.swift, Sodam/Sodam/Setting/SettingsViewController.swift, Sodam/Sodam/Setting/View/SettingTableViewCell.swift
앱재실행시 사용자가 마지막에 설정한 시간이 안뜨는 버그 해결
알림 울릴 시 뱃지 안뜨는 이슈도 수정중입니다~!ㅠㅜ
=> [Fix] 앱재실행시 사용자가 마지막에 설정한 시간이 안뜨는 버그 해결

Sodam/Sodam/Manager/FileError.swift, Sodam/Sodam/Manager/ImageManager.swift
`imagePath`에 해당하는 이미지를 삭제하는 메소드를 구현했습니다.
=> [Feat] FileManager로 이미지 삭제 구현

.gitignore
프로비저닝 파일이 추가되는걸 방지하고자 깃 이그노어에 추가했습니다.
=>  [Chore] 프로비저닝 파일 제외

Sodam/Sodam.xcodeproj/project.pbxproj
=> [Fix] pbxproj 파일 복구

Sodam/Sodam/Setting/SettingsViewController.swift
소담 앱 스토어 링크로 연결 수정하였습니다.
배포전이라 연결은 안되고 있는게 맞습니당!
=> ✏️ [Modify] 소담 앱스토어 링크 연결

Sodam/Sodam.xcodeproj/project.pbxproj, Sodam/Sodam/Configuration/Info.plist, Sodam/Sodam/HappinessDetail/HappinessDetailView.swift, Sodam/Sodam/HappinessList/HappinessListView.swift
=> [Feat] 항상 화이트모드로 유지

Sodam/Sodam/Configuration/Info.plist
=> [Feat] 화이트모드로 유지 재작업

Sodam/Sodam/Setting/SettingsViewController.swift
- 앱 초기진입시 알림 허용 안함 -> 이후 알림시간 설정시 -> 기본 설정으로 이동하여 알림 허용하도록 로직 추가
- 앱 초기진입시 알림 허용 안한 경우 토스트창 어디에 적용할지 확인 후 적용 필요합니다
=> [Fix] 앱 초기진입시 알림 허용안한 체크 후 알림시간 설정시 기본 설정 뷰로 이동하도록 추가

Sodam/Sodam/HappinessList/HappinessCell.swift, Sodam/Sodam/HappinessList/HappinessListView.swift, Sodam/Sodam/HappinessList/HappinessListViewModel.swift, Sodam/Sodam/Manager/ImageManager.swift, Sodam/Sodam/Repository/HappinessRepository.swift
행복 리스트 뷰에서 셀 탭을 했을 때 화면이 멈추는 현상을 고치기 위해 cell 파일을 분리하였습니다.
=> [Fix] 행복 리스트 뷰 셀 분리

Sodam/Sodam.xcodeproj/project.pbxproj
=>  [Modify] 오타 수정

Sodam/Sodam/HappinessList/HappinessCell.swift, Sodam/Sodam/Main/View/CustomTabBarController.swift, Sodam/Sodam/Main/View/ShowToast.swift
- 탭바 틴트컬러 변경, 토스트 오토레이아웃 재설정, 리스트뷰 폰트컬러 블랙색상으로 변경
=> [Refactor] 탭바 틴트컬러 변경, 토스트 오토레이아웃 재설정

Sodam/Sodam/WriteView/WriteViewController.swift
카메라 버튼, 이미지 버튼에 따른 알럿 타이틀 문구 분기 처리 했습니다.
| <img src="https://github.com/user-attachments/assets/a9b54f16-85c0-47d3-bed8-59907cf3f399" alt="이미지1" width="300"> | <img src="https://github.com/user-attachments/assets/3bc60ab6-3e43-4e5f-a863-735c8a91c0ed" alt="이미지2" width="300"> |
|-------------------------------------------------------|-------------------------------------------------------|
=> [Modify] 알럿 케이스 분기

Sodam/Sodam/Delegate/AppDelegate.swift, Sodam/Sodam/Manager/UserDefaultsManager.swift, Sodam/Sodam/Setting/SettingViewModel/SettingViewModel.swift
앱 재실행시 권한 허용 토스트가 뜨는 버그 수정
UserDefaultsManager에 권한 허용 여부 저장, 불러오기 추가하고
toast가 뜰만한 곳곳에 UserDefaultsManager를 계속 추가및 불러오기 해줘야하네용..!
=> [Fix] 앱 재실행시 토스트가 뜨는 버그 수정

Sodam/Sodam/Extension/+IPhoneCategory.swift, Sodam/Sodam/Model/DTO/HangdamDTO.swift, Sodam/Sodam/View/TabBar/CustomTabBar.swift, Sodam/Sodam/View/TabBar/CustomTabBarController.swift
=> [Refactor] 아이폰 기기별 탭바 크기 설정

Sodam/Sodam/View/Storage/HangdamEmptyView.swift, Sodam/Sodam/View/Storage/HangdamStorageView.swift
=> [Fix] 행담이 보관함 emptyview 작은 화면 대응

Sodam/Sodam/View/Main/MainView/Helper/MainMessages.swift, Sodam/Sodam/View/Main/MainView/MainView.swift
- 새로운 랜덤메세지 10개 추가
- 줄바꿈 쉼표기준으로 되는거 삭제하고 \n 작업으로 했습니다. 줄바꿈을 위해 부자연스럽게 쉼표가 들어가는게 마음에 들지 않아서요!
- NSMutableParagraphStyle 를 이용해서 줄 간격 설정을 했습니다. 
UILabel 을 사용할 때 기본적으로 텍스트 속성들을 하나하나 지정할 수 있긴 하지만 NSAttributedString을 사용하면 한번에 다양한 텍스트 스타일을 적용할 수 있다고 합니다. 
그래서 messageLabel에 text속성이 있는데, attributedText에도 속성을 설정하면 중복이 되어버리니 중복 될 폰트와 폰트컬러는 NSAttributedString에 넣고 , numberOfLines속성은 딕셔너리에 포함이 되지 않아서 별개로 다뤄져아한다고 하여 UILabel에 남겨두었습니다!
- 수정 전, 수정 후 입니다.
<p align="center">
</p>
추가 한 메세지 반말이 컨셉 와르르 느낌이라고 피드백 받아서 다시 공손히 존댓말로 수정해봤습니다!
=> [Refactor] 메인 메세지 추가 및 수정, 줄 간격 넓히기

Sodam/Sodam.xcodeproj/project.pbxproj, Sodam/Sodam/Configuration/en.lproj/InfoPlist.strings, Sodam/Sodam/Configuration/ko.lproj/InfoPlist.strings
- 앱 이름 현지화 했습니다.
- 접근 권한 메세지 수정했습니다.
=> [Chore] 접근권한 메세지 수정 및 앱 이름 현지화

Sodam/Sodam/View/List/HappinessList/HappinessListView.swift, Sodam/Sodam/View/List/HappinessList/HappinessListViewModel.swift, Sodam/Sodam/View/Storage/HangdamGridView.swift, Sodam/Sodam/View/TabBar/CustomTabBarController.swift
행복 리스트 뷰 리로드 코드에 이름 최신화가 없던 부분 수정
최대한 빠르게 버그 해결에만 집중했습니다.
그래서 안 좋게 수정된 부분이 존재하는데(의존성이 명확히 안 보이는 점) 바로 리팩터링 들어가겠습니다
=> [Fix] Happiness list view sync bug
