Sodam/Sodam/Main/View/CustomTabBar.swift, Sodam/Sodam/Main/View/MainMessages.swift, Sodam/Sodam/Main/View/MainView.swift, Sodam/Sodam/Main/ViewModel/CustomTabBarController.swift, Sodam/Sodam/Main/ViewModel/MainViewController.swift
전 pr에서 받은 피드백 ( 오타 수정, class 앞에 final 붙이기, 메인화면 이미지뷰 동적으로 만들기) 수정 완료했습니다.
1. 문구는 앱 실행 처음에만 firstMessage 가 나오고 나머지 20개의 문장이 랜덤으로 나옵니다.
2. 중복 클릭 방지 코드를 넣었습니다.
이미지뷰를 처음 눌렀을 때 초기 Bool 값을 true로 두다가 터치 후에 false가 되면 기존 랜덤문구들이 나오게 했는데  나중에는 알이 부화되었는지의 여부로 저걸 변경할 예정입니다. ( 안그러면 처음 들어올 때마다  firstMessage 가 나와서)
그리고 여러번 버튼을 눌러서 빠르게 변환되지 않게 한번 이미지뷰를 탭하면 2초간 탭할 수 없게 비활성화 시켜서 앱이 불필요한 작업을 반복하지 않게 했습니다.
- 모달 띄우는 기능
- 최초 작성 클릭 시 알럿 설정
=> [Feat] 메인화면 랜덤 문구 설정 및 피드백 반영

Sodam/Sodam/Main/ViewModel/CustomTabBarController.swift
스크롤뷰를 포함한 뷰로 탭했을 때 탭바의 배경 색상이 바뀌는 버그 수정
> 이런 현상이 있었는데 고쳤습니다.
튜터님과 진홍님의 조언 + 클로드의 도움으로 해결
=> [Fix] TabBar Appearance 설정

Sodam/Sodam/HangdamStatusView.swift, Sodam/Sodam/HangdamStorage/HangdamGridView.swift, Sodam/Sodam/HangdamStorage/HangdamStorageView.swift, Sodam/Sodam/HangdamStorage/MockHangdam.swift, Sodam/Sodam/HangdamStorage/TestView.swift
- viewBackground color 추가
- 행담이 상태뷰에서 행담이 이미지 크기 줄임
- font set 마루부리로 바꾸고 굵기 별로 지정
- 자잘한 간격 수정
- 행담이 상태뷰 및 행담이 grid에 `NavigationLink` 적용 : `TestView` 사용
| before | after |
| ----- | ----- |
| <img src="https://github.com/user-attachments/assets/f6db7713-763b-47a9-bb5f-2034f3730867" width=430> | <img src="https://github.com/user-attachments/assets/d164c12d-8bf5-4f5f-92e7-919d50f2cab5" width=430> |
데이터 바인딩 및 행담이 기억 리스트 뷰 merge 시 코드 수정 필요
=> [Refactor] 행담이 보관함 뷰 UI 업데이트 및 Navigation 추가

Sodam/Sodam/HappinessList/HappinessListView.swift
무능력한 `Xcode`가 잡아내지 못하고 원인 불명 컴파일 에러만 내고 있었으나 +Date 의 계산 프로퍼티 네이밍 변경이 반영이 되지 않은 것이 원인인 것을 발견하고 고침
- 에러 메시지
- 실제 원인
> `toString` - `toFormattedString`으로 변경된 내용을 반영하지 않고 있었음. 이 부분을 캐치하지 못하고 타입 체크가 안된다는 컴파일 에러만 떠서 혼란스러웠던 상황
=> [Fix] 컴파일 에러 해결

Sodam/Sodam/Extension/+Notification.swift, Sodam/Sodam/Main/View/MainViewModel.swift, Sodam/Sodam/Repository/HappinessRepository.swift
`WriteView`에서 행복이 작성완료가 되는 시점에 레벨업 순간인지 체크하고 레벨업 할 때 `MainView`에 알려주는 이벤트 구현
- `HappinessRepository`에서 행복 개수를 검사하여 `Notification`을 `post`하고, `MainViewModel`에서 `observe` 합니다.
- 레벨업 이벤트와 함께 레벨 몇으로 성장하는지 `Int` 값을 함께 전달합니다.
- `MainViewModel`에서 `level` 값을 활용하여 레벨에 따라 메시지가 나오도록 처리하시면 될 거 같습니다.
- 추가로, 레벨에 따라 gif 변하는 로직을 여기서 함께 처리하도록 옮기는 것도 괜찮겠다는 생각이 들었습니다.
=> [Feat] NotificationCenter로 레벨업 이벤트 전달

Sodam/Sodam/Manager/UserDefaultsManager.swift, Sodam/Sodam/WriteView/WriteModel.swift, Sodam/Sodam/WriteView/WriteViewController.swift, Sodam/Sodam/WriteView/WriteViewModel.swift
글 작성 취소시 UserDefaults에 임시 저장, 작성 완료시 CoreData 영구 저장하도록 하였습니다.
| <img src="https://github.com/user-attachments/assets/f30754d1-9061-407a-ab9a-ce074a3b11ff" alt="임시저장 테스트" width="200"> | <img src="https://github.com/user-attachments/assets/e8e0912f-ee90-4f51-b202-a06ef87bee0e" alt="작성 완료 테스트" width="200"> | <img src="https://github.com/user-attachments/assets/08035b62-6e85-4eb9-b72f-4e12519a0183" alt="사진 추가 알럿 테스트" width="200">
|-------------------------------------------------------|-------------------------------------------------------|-------------------------------------------------------|
임시 저장 테스트 | 작성 완료 테스트 | 사진 추가 제한 알럿
- UserDefaultsManager에 ImagePath 저장 하는 부분 코어데이터와 같게 배열로 변경하였습니다. (여기서 혹시 문제 되는 부분 있는지 확인 필요할 것 같습니다!)
- 작성 완료시 UserDefaults에 저장된 내용을 비우기 위해 UserDefaultsManager에 …
=> [Feat] 글 임시저장 및 작성 완료 기능 구현

Sodam/Sodam/CoreData/DTO/HangdamDTO.swift, Sodam/Sodam/Main/View/MainMessages.swift, Sodam/Sodam/Main/View/MainViewController.swift, Sodam/Sodam/Main/View/MainViewModel.swift
- MainViewModel에서 DTO 관리
- HangdamRepository를 통해 HangdamDTO 데이터를 가져오고, 이를 @Published 속성으로 관리.
- HangdamDTO의 데이터 변경이 일어나면 Combine을 통해 알림을 전달.
- MainViewController에서 viewModel.$hangdam과 viewModel.$message를 구독.
- 데이터가 변경되면 UI를 업데이트하는 코드(updateNameLabel, updateGif, updateMessage)를 호출해서 즉시 반영하게 함
- 앱이 재실행 될때 알 상태인 GIF 가 나왔던 것 해결
데이터의 구조와 변환 로직이 DTO 내부로 캡슐화되어서 더이상 ViewModel과 ViewController가 데이터 변환을 걱정하지 않아도 되게 했습니다!
- 알을깨고 나왔을 때 이름이 표시 되지 않아서 이름 저장 후 데이터를 다시 로드하는 코드를 추가작성하여 정상출력 되는것 확인했습니다
=> [Refactor] DTO를 이용해 컨트롤러와 뷰모델 바인딩 완료

Sodam/Sodam/Delegate/AppDelegate.swift, Sodam/Sodam/Delegate/SceneDelegate.swift, Sodam/Sodam/Main/View/MainViewModel.swift, Sodam/Sodam/Manager/LocalNotificationManager.swift, Sodam/Sodam/Setting/SettingViewModel/SettingViewModel.swift, Sodam/Sodam/Setting/SettingsViewController.swift
알림이 울리고 알림 미확인 시 뱃지 +1씩 증가
알림이 울리고 바로 알림 확인 시 뱃지 숫자 초기화
알림이 울리고 뱃지 숫자가 쌓인 상태에서 설정 화면으로 진입 시 뱃지 숫자 초기화
설정화면으로 진입 했을때 뱃지가 초기화 되도록하였는데 해당 로직이 어색한지, 
탭바 설정아이콘에도 동일하게 뱃지 표시가 되면 좋을거같긴한것같습니다..(가능한지 잘 모르겠어요)
앱 진입시 초기화되는게 나은지 고민이 되는 부분입니다..!
=> [Fix] 알림 울리면서 뱃지 +1 증가, 앱 진입시 뱃지 초기화 수정

Sodam/Sodam/CoreData/DTO/HangdamDTO.swift, Sodam/Sodam/Extension/+Image.swift, Sodam/Sodam/HangdamStatusView.swift, Sodam/Sodam/HangdamStorage/HangdamGridView.swift, Sodam/Sodam/HangdamStorage/HangdamStorageView.swift
- 행담이 상태 : 레벨 별 행담이 이미지와 레벨 별 행담이 명칭 적용
- 행담이 보관함 : 행담이 기억 저장한 기간 바인딩
- 다 자란 행담이 수 뷰 추가
행담이 레벨 별 명칭의 경우 HangdamDTO에 계산 프로퍼티로 추가하였습니다.
1. 메인 뷰에 "점잖스러운" 표현 수정이 필요합니다. 또, "변신"보다 "성장"이라는 표현이 자연스러울 거 같다는 제안 드립니다.
2. "멍담이"라고 지었을 때 행복 리스트 뷰로 이동하면 "멍담이담이"라고 표시되기 때문에 사용자로 하여금 "담이" 앞에 붙을 명칭을 짓도록 확실하게 유도할 필요가 있습니다.
3. 논의하면 좋을 점
- 하루에 기억 하나만 기록하도록 조치 필요성
- 현재 성장 중인 행담이가 가진 기억은 삭제하지 못하도록 막는 것 필요성
=> [Feat] 행담이 상태 뷰, 보관함 뷰 데이터 바인딩

Sodam/Sodam/CoreData/CoreDataManager.swift, Sodam/Sodam/HappinessList/HappinessListView.swift, Sodam/Sodam/Main/Utilities/AlertManager.swift, Sodam/Sodam/Main/View/MainMessages.swift, Sodam/Sodam/Main/View/MainView.swift, Sodam/Sodam/Main/View/MainViewController.swift, Sodam/Sodam/Main/View/MainViewModel.swift
- 이름 4글자로 제한 (영어 8글자 - 넉넉하게 해도 크기가 크지 않아서)
- "~ 담이" 로 나올 수 있게 텍스트필드상에서 바로 저장하도록 구현
- 이름 지어줄 때도 텍스트필드 옆에 "담이" 글자 나오게 함 
- 오늘 날짜에 등록된 소확행 기록이 있으면 다음날에 작성가능하도록 유저디폴츠로 구현
- 작성 완료 후 작성하기 버튼 탭시 작성 완료 알럿창 구현
버튼 살짝 탭바랑 가깝게 거리 줄임, se3 테스트시 글이 3줄이 나올 때 버튼에 겹쳐서 보이지 않아서 수정함
- 이름 받침 있어도 가능한 부분 스크린샷 및 코어데이터 없이 텍스트필드상에서 저장되는 것 확인했습니다.
- 원활한 테스트를 위해서 유저디폴츠로 1일1작성 구현한 부분은 주석처리했습니다 바로 풀 받아도 영향가지 않게 테스트 3번 했습니다!
- 어색한 부분 있으면 말씀해주세요
=> [Feat] ~담이 이름으로 나올 수 있게 수정 및 1일1작성 구현

Sodam/Sodam/CoreData/DTO/HangdamDTO.swift, Sodam/Sodam/HangdamStatusView.swift, Sodam/Sodam/HangdamStorage/HangdamGridView.swift, Sodam/Sodam/Main/View/MainMessages.swift, Sodam/Sodam/Main/View/MainViewController.swift, Sodam/Sodam/Main/View/MainViewModel.swift, Sodam/Sodam/WriteView/WriteView.swift, Sodam/Sodam/WriteView/WriteViewController.swift, Sodam/Sodam/WriteView/WriteViewModel.swift
- 보관된 행담이의 기억을 삭제해도 레벨이 down되지 않게 처리
- 행담이 새로 생성되었을 때 기록한 행복이 이미 보관된 행담이에게 추가되는 버그 수정
- `Main` 화면에서 레벨업 상황과 이름이 없는 경우를 제외하고 랜덤 메시지 출력되도록 처리
- 행담이 상태뷰, 행담이 보관함에서 `endDate`까지 표시되어 텍스트가 길어지는 경우 폰트 크기가 작아지도록 처리
| before | after |
| ----- | ----- |
| ![Screenshot 2025-02-03 at 20 23 51](https://github.com/user-attachments/assets/830005e7-59a1-496f-8bf8-9e41cf31c194) | ![Screenshot 2025-02-03 at 20 24 19](https://github.com/user-attachments/assets/19fc6573-c36c-46bc-a430-053f1b81d010) |
=> [Fix] reload 버그와 endDate UI 버그 수정

Sodam/Sodam/Extension/+Notification.swift, Sodam/Sodam/Main/View/MainViewController.swift, Sodam/Sodam/WriteView/WriteViewController.swift
시연님이 Xcode Instruments로 발견하신 메모리 누수 해결했습니다. 작성 완료 alert의 completion에 [weak self] 약한 참조 처리 했습니다.
=> [Fix] WriteViewController 메모리 누수 해결

Sodam/Sodam/Delegate/AppDelegate.swift
앱 첫진입시 권한 허용여부에 따른 토스트 표시 추가
허용누른 경우 "알림 시간 설정이 가능합니다." 표시
허용안함 누른 경우 "알림 권한이 거부되었습니다." 표시
=> [Modify] 앱 첫진입시 권한 허용여부에 따른 토스트 표시 추가

Sodam/Sodam/Delegate/AppDelegate.swift, Sodam/Sodam/Manager/UserDefaultsManager.swift, Sodam/Sodam/Setting/SettingViewModel/SettingViewModel.swift, Sodam/Sodam/Setting/SettingsViewController.swift
알림 권한 설정 내용 추가
1. 알림권한 허용안한상태로 앱 첫진입시와 재진입했을 경우 디폴트가 토글 off
2. 알림권한 허용 된 상태일때 앱 첫 진입시에는 사용자가 설정 안한상태에는 디폴트가 토글 on, 알림시간은 21:00
3. 알림권한 허용 된 상태일때 아이폰설정에서 알림허용 off 후 앱 진입시 앱내 설정 off
4. 앱 내 설정 off 시 시간 셀 숨김 안되는 오류 수정
5. 앱 첫 진입시 알림 허용, 이후 앱내 알림 토글 off 로 하고 다시 On 했을때 설정으로 이동하는 알럿이 안뜨도록 설정
✅ 런치스크린 종료 시 토스트가 깜빡이는 이슈 해결 계획
**현재이슈**
- AppDelegate에서 알림 권한 팝업을 일정 시간 후 실행하도록 설정하여 런치스크린 종료 후 토스트가 깜빡이는 문제를 방지함.
**추후수정**
- 현재 런치스크린이 사라질 때 토스트 팝업이 깜빡이는 문제가 발생하여, 팀원 및 튜터님과 논의 후 리팩토링을 적용하기로 결정
- 권한 팝업을 AppDelegate가 아닌 MainViewController에서 처리하도록 수정 예정
- 알림 권한 요청 로직을 LocalNotificationManager에서 관리하도록 변경
- 런치스크린과 권한 팝업이 겹치지 않도록 더 안정적인 방식으로 개선
리팩토링을 통해 더 구조적으로 정리하고, 사용자가 자연스럽게 권한 요청을 경험하도록 개선할 예정입니담!
=> [Fix] 앱 첫 진입 후 사용자가 알림 시간설정은 안한상태일때 기본 시간 설정 (저녁 9시)

Sodam/Sodam/View/Main/WriteView/WriteView.swift, Sodam/Sodam/View/Main/WriteView/WriteViewController.swift, Sodam/Sodam/View/Main/WriteView/WriteViewModel.swift
- 레이아웃 수정 전에 코드 먼저 정리 했습니다. 코드 정리는 [Style]로, 레이아웃 수정은 [Modify]로 커밋 했습니다.
- 텍스트뷰 크기를 동적으로 조절하게 하여 레이아웃이 겹치지 않도록 하였습니다.
- 사진을 담을 CollectionView에 사진이 없을 때는 안보이도록 숨김처리 하고, 그만큼 텍스트뷰 크기를 늘어나도록 했습니다.
- 파란 테두리는 글 작성을 위한 textView 입니다.
- 초록색 테두리는 사진이 담기는 collectionVIew 입니다.
- 빨간색 테두리는 버튼들을 담은 UIView 입니다.
- 테두리는 UI 크기 확인을 편하게 하기 위해 추가한 부분으로 실제 코드에는 지우고 커밋 하였습니다!
- 기존 작성뷰 코드들이 생각나는 대로 작성해둔 면이 있어서, 기능별로 모아두느라 코드 정리를 한 번 했습니다.
- 코드 정리하느라 수정 사항이 많은데, 레이아웃 변경에 대한 코드리뷰는 [Modify] 커밋을 보며 리뷰 해주시면 편할 것 같습니다.
- 기존에는 텍스트뷰의 상단과 높이 제약 조건 값을 지정해 크기를 고정시켰는데, 높이 값을 지정하지 않고 하단을 collectionVIew 혹은 containerView의 상단과 맞추어 조절되도록 하였습니다.
- collectionView는 사진을 띄우는 역할을 하였는데, 사진이 없을 때도 공간을 차지하여, 글을 입력하려고 이 부분을 터치하면 아무 동작도 하지않는 경우가 생길 수 있었습니다. 사진이 없을 땐 collectionView를 숨김 처리하여 textView 크기를 최대한 늘렸습니다.
- 하단 버튼 간격이 키보드에 딱 붙어있던 걸 …
=> [Fix] 작성뷰 레이아웃 수정

Sodam/Sodam/Model/Manager/CoreDataManager.swift, Sodam/Sodam/Model/Repository/HappinessRepository.swift, Sodam/Sodam/View/List/HappinessList/HappinessListView.swift, Sodam/Sodam/View/List/HappinessList/HappinessListViewModel.swift
`Core Data`의 `NSPredicate`를 사용한 필터링과 `NSSortDescriptor`를 사용한 정렬을 통해 행복 리스트 정렬 변경 적용
> 최근에 추가한 행복이 맨 위에 있는 모습
행복 배열을 옵셔널로 반환했던 메소드들을 `some` case를 반환하도록 수정하고, 예외 상황에서는 빈 값 `[]`을 반환하도록 처리했습니다.
=> [Modify] 최근에 추가한 행복이 리스트 맨 위에 보이도록 처리

Sodam/Sodam/Model/DTO/DTOMapper.swift, Sodam/Sodam/Model/DTO/HangdamDTO.swift, Sodam/Sodam/Model/DTO/HappinessDTO.swift, Sodam/Sodam/Model/Manager/CoreDataManager.swift, Sodam/Sodam/Model/Repository/HangdamRepository.swift, Sodam/Sodam/Model/Repository/HappinessRepository.swift
행담이와 행복의 dto - entity 간 mapping을 담당하는 객체 정의
Entity를 extension하여 `toDTO`라는 계산 프로퍼티를 통해 편하게 Entity → DTO 변환을 한다고 생각했던 코드가 (내가)편하기만 한 코드일 뿐 DTO로 하여금 Entity에 의존하게 된다는 사실을 간과했습니다. 튜터님의 프로젝트 피드백 내용을 반영하여 매핑을 담당하는 구조체를 따로 정의하여 repository에서 mapper를 통해 entity를 dto로 변환하도록 리팩토링 했습니다.
+ 행복 dto - entity 변환을 `CoreDataManager`에서 직접 하던 것을 mapper에게 역할 분담했습니다.
(행담이는 dto - entity 방향 생성이 이루어지지 않기 때문에 toEntity를 구현하지 않았습니다.)
=> [Refactor] DTO mapper

Sodam/Sodam/Delegate/AppDelegate.swift, Sodam/Sodam/Delegate/SceneDelegate.swift, Sodam/Sodam/Model/Manager/AlertManager.swift, Sodam/Sodam/Model/Manager/LocalNotificationManager.swift, Sodam/Sodam/Model/Manager/ToastManager.swift, Sodam/Sodam/Model/Manager/UserDefaultsManager.swift, Sodam/Sodam/View/Main/MainView/MainViewController.swift, Sodam/Sodam/View/Setting/SettingViewModel.swift, Sodam/Sodam/View/Setting/SettingsViewController.swift
1. LocalNotificationManager 싱글턴으로 리팩토링
2. ToastManager 싱글턴 추가
아래와 같은 버그는 추가적으로 수정예정입니다
=> [Refactor] LocalNotificationManager 리팩토링, ToastManager 추가

Sodam/Sodam/View/List/HappinessList/HappinessCell.swift, Sodam/Sodam/View/List/HappinessList/HappinessListView.swift
happiness cell에서 navigationLink를 처리하는 대신 View를 구성하는 것에 집중시키고
happiness list에서 navigationLink를 사용, label에 happiness cell을 사용했습니다.
아직 충분히 테스트가 이뤄지지 않아서(첫 글에서 팅기는 부분이 수정된 부분 변경함) 아직 주석처리한 채로 놔두었습니다.
추후 삭제를 잊지 않게 이슈에 따로 체크사항 넣어두었습니다.
=> [Refactor] happiness cell

Sodam/Sodam/View/Main/WriteView/ImageCollectionViewCell.swift, Sodam/Sodam/View/Main/WriteView/WriteView.swift, Sodam/Sodam/View/Main/WriteView/WriteViewController.swift
- 긴 글 입력했을 때 줄 간격 조절했습니다.
- 버튼 색깔 회색인거랑, 높이가 과하게 위로 올라가 있는 부분이 어색하다고 생각해서 수정했습니다.
- 줄 간격은 swiftUI에서 작성한 linespacing과 같아지도록 수식을 사용했습니다.
- 버튼 색을 gray에서 날짜나 입력한 글자 색과 같은 darkGray로 변경하였습니다
- 이미지 삭제 버튼의 trash 아이콘이 눈에 잘 안띄어서 색깔을 red로 변경했습니다. 기존에는 black이었습니다.
- 버튼 높이 안전영역으로부터 60 띄우도록 했는데, se에서도 그렇고 홈인디케이터 있는 기종에서도 그렇고 과하게 띄워져 있는 것 같아서 20으로 줄였습니다.
=> [Modify] 줄 간격 및 버튼 색깔 수정

Sodam/Sodam/View/List/HappinessDetail/HappinessDetailView.swift, Sodam/Sodam/View/List/HappinessList/HappinessCell.swift
업데이트 배포를 위해 진홍님 작업 merge 안되고 그냥 closed 됐던 PR 다시 적용해서 올립니다.
| HappinessListView | HappinessDetailView |
| ----- | ----- |
| <img src="https://github.com/user-attachments/assets/fc545828-01e2-4f52-b61e-86b0eb2b6e86" width=430> | <img src="https://github.com/user-attachments/assets/e8cc798d-9c4b-48d5-a515-441aaed63e82" width=430> |
=> [Modify] 행복 디테일 뷰 폰트와 줄 간격 적용

Sodam/Sodam/Helper/TabBarHelper.swift, Sodam/Sodam/View/List/HappinessDetail/HappinessDetailView.swift, Sodam/Sodam/View/List/HappinessList/HappinessListView.swift, Sodam/Sodam/View/Storage/HangdamStorageView.swift
민석님이 발견하신 디테일 뷰에서 스크롤 문제
- 현상 : 스크롤을 맨 밑까지 내렸음에도 불구하고 내용이 끝까지 보이지 않음(스크롤이 다시 위로 튕기는 것처럼 보임)
- 원인 : 탭바가 화면의 맨 밑을 가림
- 해결 방법 : 네비게이션이 쌓였을 때 탭바를 가린다.
> 원인 분석 : 탭바가 화면의 맨 밑을 가리는 현상 발견
> 해결 화면 : 디테일 뷰 진입시 탭바 hide
- `HappinessListView`가 기록탭과 보관탭에서 재사용되는데, 선택된 탭 상황에 따라 탭바가 보이거나/숨기거나 해야해서 이걸 custom modifier로 처리했습니다.
- 진홍님이 구현하신 `getRootTabBarController()` 메소드를 `TabBarHelper`로 옮겼습니다.
=> [Fix] Navigation 쌓였을 때 Tabbar 처리

Sodam/Sodam/View/Storage/HangdamStorageView.swift
보관함 뷰에 첫 진입 시 왼쪽 상단에서 뷰가 로드되는 현상 수정했습니다.
해결법은 뷰의 frame을 미리 설정해두어 로드되는 데이터에 따라 frame이 변경되지 않도록 했습니다.
=> [Fix] Storage view rendering bug

Sodam/Sodam/View/List/HappinessDetail/HappinessDetailView.swift
Back버튼을 숨기고 "기억들"이라는 이름으로 별개의 버튼을 만드는 과정에서 뒤로가기 제스처가 소실된 버그 수정
Back버튼을 다시 살리고 대신 tint컬러 지정 했습니다.
back버튼 이름은 이전 네비게이션의 타이틀을 따르는데 수정하려고 하니 UIKit과 연결해야 해서 그냥 Back버튼으로 놔두었습니다.
=> [Fix] Back action gesture bug

Sodam/Sodam/View/Main/WriteView/WriteView.swift, Sodam/Sodam/View/Main/WriteView/WriteViewController.swift
1. 작성 완료 시 키보드가 잠깐 다시 나타나는 현상 해결
2. 메모리누수 해결해놨더니 다시 발생시킨 부분 다시 해결😛
| before | after |
| ----- | ----- |
| ![Screen Recording 2025-02-18 at 15 15 18](https://github.com/user-attachments/assets/bd70b816-e239-49fb-9644-547ed95c4845) | ![Screen Recording 2025-02-18 at 16 07 13](https://github.com/user-attachments/assets/4a65b508-15c5-4449-bb0a-3b8a96a4c533) |
| before | after |
| ![leak](https://github.com/user-attachments/assets/fffced73-0408-4e41-aaf7-ae66783de369) | ![Screenshot 2025-02-18 at 16 12 26](https://github.com/user-attachments/assets/0d4f56a7-343e-49a1-8f50-1e074b5bb823) |
작성 완료 버튼을 누르는 순간 `UITextView`의 입력 모드를 끝내 키보드를 내리도록 하는 `resignFirstResponder` 메소드를 이용하여 해결했습니다.
=> [Fix] 작성 뷰 키보드 버그 수정 / 메모리누수 해결

Sodam/Sodam/View/Main/MainView/MainViewController.swift, Sodam/Sodam/View/Main/WriteView/WriteViewController.swift
모달 나올 때 모달 뒷 배경에 상태표시줄이 보이도록 수정했습니다.
| ![이미지1](https://github.com/user-attachments/assets/7ad42e40-a9cf-48d6-9927-a06bc542b18f) | ![이미지2](https://github.com/user-attachments/assets/a41fadd5-f637-48fa-9f36-0d1fee8fe5b4) |
|--------------------------|--------------------------|
상태표시줄 검은색으로 표시되도록 했습니다.
- 가장 중요한 건 메인뷰에서 작성뷰 모달 띄울 때, modalPresentationCapturesStatusBarAppearance를 true로 설정하는 것이었습니다. 모달이 표시될 때 상태 바 스타일을 해당 모달이 결정하도록 하는 속성이라고 합니다.
- 저희가 다크모드를 지원하지 않아 window 배경색이 항상 하얀색일테니, 상태바 속성을 검은색이 되도록 고정해놓은 상태입니다. 만약 다크모드 지원한다고 하면 return을 traitCollection.userInterfaceStyle를 통해 조절하면 될 것 같습니다..!
=> [Fix] 작성뷰 모달 상태표시줄 안보이던 것 수정

Sodam/Sodam/Model/Manager/Alert/AlertTypes.swift, Sodam/Sodam/View/Main/WriteView/WriteView.swift, Sodam/Sodam/View/Main/WriteView/WriteViewController.swift
- 글자수 제한 기능 추가했고, 일단 500자로 제한 하였습니다.
- 작성된 글자수도 0 / 500 이런식으로 표기되도록 추가했습니다.
| <img src="https://github.com/user-attachments/assets/3c3f6a95-0d3e-4495-ac38-26936f32c646" alt="이미지1" width="300"> | <img src="https://github.com/user-attachments/assets/bb8c850c-da19-4a0c-9f2d-145d2ca61caf" alt="이미지2" width="300"> | <img src="https://github.com/user-attachments/assets/19361a42-0600-47df-bc11-daf8c8a8e3ec" alt="이미지2" width="300"> |
|-------------------------------------------------------|-------------------------------------------------------|-------------------------------------------------------|
|아무 입력도 안 했을 때|글자 입력했을 때 카운트 증가|키보드 없을 때 레이아웃|
| <img src="https://github.com/user-attachments/assets/f44b6b83-48a4-4fda-bd28-6c309e2e8860" alt="이미지1" width="250"> | <img …
=> [Feat] 글자수 제한 기능 및 입력한 글자수 표기 추가

Sodam/Sodam/Delegate/SceneDelegate.swift, Sodam/Sodam/Model/Manager/Alert/AlertManager.swift, Sodam/Sodam/Model/Manager/LocalNotificationManager.swift, Sodam/Sodam/Model/Manager/UserDefaultsManager.swift, Sodam/Sodam/View/Main/MainView/MainViewController.swift, Sodam/Sodam/View/Main/MainView/MainViewModel.swift, Sodam/Sodam/View/Main/WriteView/WriteViewModel.swift, Sodam/Sodam/View/Setting/SettingTableViewCell.swift, Sodam/Sodam/View/Setting/SettingViewModel.swift, Sodam/Sodam/View/Setting/SettingsViewController.swift
- 일기 작성이 된 경우 알림시간이 설정되어있어도 알림 X (하루기준) 앱실행, 포그라운드, 백그라운드 모두 적용완료
- 다음날 일기 작성이 안된 경우 사용자가 마지막 설정한 알림시간이 있다면 알림 O 앱실행, 포그라운드, 백그라운드 모두 적용완료
- [LocalNotificationManger 리팩토링](https://github.com/Sodamii/Sodam/commit/aba7d8ec86ca916baec9d89e099415c8ceb29022)
1. MainViewModel 기존 코드 UserDefaultManager로 수정 (이미지상 오류는 무시하셔도됩니다! pr 올리고 캡쳐해서 나오는 오류입니다.)
2. 지혜님이 달아주신 리뷰도 수정완료하였습니다!
=> [Fix] 일기 작성 시간 확인 후 알림시간 전 작성완료 시 알림 안울리게 코드 수정

Sodam/Sodam/Delegate/SceneDelegate.swift, Sodam/Sodam/Model/Manager/LocalNotificationManager.swift, Sodam/Sodam/Model/Manager/UserDefaultsManager.swift, Sodam/Sodam/View/FontSetting/FontSettingTableViewCell.swift, Sodam/Sodam/View/FontSetting/FontSettingViewController.swift, Sodam/Sodam/View/FontSetting/FontSettingViewModel.swift, Sodam/Sodam/View/Setting/Helper/Setting.swift, Sodam/Sodam/View/Setting/SettingTableViewCell.swift, Sodam/Sodam/View/Setting/SettingViewModel.swift, Sodam/Sodam/View/Setting/SettingsViewController.swift, Sodam/Sodam/View/TabBar/CustomTabBarController.swift
- 설정 > 폰트설정 기능 추가하였습니다.
- 의견중에 Cell 선택했을때 효과를 아직 확정안한거같은데 이부분까지만 확정하고 최종 반영하겠습니다.
- 네비게이션 타이틀은 UILabel로 최종 반영하게 된 이유는 appearance로 사용시 Font부분만 나누면 appearance를 각각 작성하거나 한곳에서 관리를 해줘야하는데 조금 시간이 걸릴거 같고, 아래와 같은 오류도 계속 뜨더라구요!  배포를 우선순위로 두어서 큰 수정이 없는 UILabel로 결정하게되었습니다!
=> [Feat] 사용자가 원하는 폰트로 설정할 수 있는 기능 추가
